[project]
name = "truespecs-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Bits232", email = "isahalamainwith@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "groq>=1.7.0",
    "httpx>=0.28.1",
    "openai-agents>=0.22.3",
    "python-dotenv>=1.2.3",
]

[project.scripts]
truespecs-agent = "truespecs_agent:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
